name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: Build and deploy

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.2.0
          run_install: false   # <- added to avoid hitting npm registry

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          VITE_BASE_PUBLIC_PATH: ${{ secrets.VITE_BASE_PUBLIC_PATH }}
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
